- Vagrantfile
- kernel/src/main/scala/org/apache/toree/boot/CommandLineOptions.scala
- kernel/src/main/scala/org/apache/toree/kernel/api/Kernel.scala
- kernel/src/test/scala/org/apache/toree/boot/CommandLineOptionsSpec.scala
- kernel/src/test/scala/org/apache/toree/kernel/api/KernelSpec.scala
- resources/compile/reference.conf
- resources/test/reference.conf
fixed https://issues.apache.org/jira/browse/TOREE-219
> Removing --spark-configuration cmd arg

- etc/examples/notebooks/magic-tutorial.ipynb
This notebook should be left with the output so users can view the documentation properly in places like github and nbviewer.
> [TOREE 277]: Added tutorial notebook for magics

- Dockerfile
- Makefile
- etc/kernel.json
- etc/pip_install/toree/toreeapp.py
Addresses https://issues.apache.org/jira/browse/TOREE-267
> Upgrading references to Spark to 1.6.1

- plugins/src/main/scala/org/apache/toree/plugins/PluginSearcher.scala
Resolves [TOREE-314](https://issues.apache.org/jira/browse/TOREE-314).
@lbustelo, @poplav, we need to add a system test with a dummy external plugin that we can add to verify this works. For now, @tigerquoll and @danrope can verify by building and running against this version of Toree for Brunel. I've been getting an AbstractMethodError with Brunel since adding this fix (indicating that it is detected) instead of no error (not loading the plugin). I posted on Gitter the comparison between a Toree magic and the Brunel magic, which showed that the Brunel magic was not compiled against a new version of Toree (even when I built it myself using `gradle assemble`).
> Updated loading of external plugins to check internal class information when recursing interfaces and super classes

- README.md
@lbustelo, @Lull3rSkat3r, can one of you merge this in?
> Fixed Travis badge to point to Toree

- protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/SparkKernelInfo.scala
> Toree default spark app name1.x

- scala-interpreter/src/main/scala-2.11/org/apache/toree/kernel/interpreter/scala/ScalaInterpreterSpecific.scala
- test_toree.py
Switching the scala completer that we use to PresentationCompilerCompleter (which is the default one in Scala 2.11).  This should allow us to get much better autocompletion.
> [TOREE-342] Switch completer

- kernel-api/src/main/scala/org/apache/toree/interpreter/Interpreter.scala
- kernel/src/main/scala/org/apache/toree/boot/layer/HandlerInitialization.scala
- kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/IsCompleteHandler.scala
- kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/interpreter/InterpreterActor.scala
- kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/interpreter/tasks/InterpreterTaskFactory.scala
- kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/interpreter/tasks/IsCompleteTaskActor.scala
- kernel/src/main/scala/org/apache/toree/utils/MessageLogSupport.scala
- kernel/src/test/scala/test/utils/DummyInterpreter.scala
- protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/IsCompleteReply.scala
- protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/IsCompleteRequest.scala
- protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/package.scala
- pyspark-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/pyspark/PySparkInterpreter.scala
- scala-interpreter/src/main/scala-2.10/org/apache/toree/kernel/interpreter/scala/ScalaInterpreterSpecific.scala
- scala-interpreter/src/main/scala-2.11/org/apache/toree/kernel/interpreter/scala/ScalaInterpreterSpecific.scala
- sparkr-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sparkr/SparkRInterpreter.scala
- sql-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sql/SqlInterpreter.scala
- test_toree.py
According to the spec here we need to implement support for is_complete_request
https://github.com/jupyter/jupyter_client/blob/4.4.0/docs/messaging.rst#code-completeness
This is i think the minimal amount required to support this.
> [TOREE-343] Added support for `is_complete_request`

- Dockerfile.system-test
- Makefile
- kernel-api/src/main/scala/org/apache/toree/interpreter/Interpreter.scala
- kernel-api/src/main/scala/org/apache/toree/interpreter/broker/BrokerState.scala
- kernel-api/src/test/scala/org/apache/toree/interpreter/broker/BrokerStateSpec.scala
- kernel/src/main/scala/org/apache/toree/boot/KernelBootstrap.scala
- kernel/src/main/scala/org/apache/toree/boot/layer/HandlerInitialization.scala
- kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/KernelInfoRequestHandler.scala
- kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/handler/KernelInfoRequestHandlerSpec.scala
- kernel/src/test/scala/test/utils/DummyInterpreter.scala
- protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/LanguageInfo.scala
- protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/SparkKernelInfo.scala
- protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/KernelInfoReply.scala
- protocol/src/test/scala/org/apache/toree/kernel/protocol/v5/content/KernelInfoReplySpec.scala
- pyspark-interpreter/src/main/resources/PySpark/pyspark_runner.py
- pyspark-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/pyspark/PySparkInterpreter.scala
- scala-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/scala/ScalaInterpreter.scala
- sparkr-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sparkr/SparkRInterpreter.scala
- sparkr-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sparkr/SparkRProcess.scala
- sparkr-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sparkr/SparkRService.scala
- sql-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sql/SqlInterpreter.scala
- test_toree.py
This continues the work done in #51
> Continuation of kernel_info_request message handling

- test_toree.py
Verifying that case classes and the dataset api work
> Added a simple integration test for Dataset Api 

- pyspark-interpreter/src/main/resources/PySpark/pyspark_runner.py
Logger doesn't have the flush method which is causing an exception when I try to use it as a stream for my project.
> Add Flush Method to Logger so it can be compliant to stream interface: JIRA TOREE-356 and TOREE-357

- kernel/src/main/scala/org/apache/toree/boot/layer/ComponentInitialization.scala
- kernel/src/main/scala/org/apache/toree/kernel/api/Kernel.scala
- kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/ExecuteRequestHandler.scala
- kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/relay/ExecuteRequestRelay.scala
- plugins/src/main/scala/org/apache/toree/plugins/PluginEvents.scala
allInterpretersReady event: fired when all interpreters have completed
their initialization
preRunCell event: fired every time a new cell is being run, unless the
silent flag is set
> [TOREE-360] fire allInterpretersReady and preRunCell events

- Makefile
Simple addition to the makefile to easily test a pip release
> Target to test a released pip package

- Makefile
- README.md
This is some minor changes to fix:
1. pip command to install from apache dist server
2. removed adding legal docs to src dist package
> Some0.1.x changes to docs and make

- kernel-api/build.sbt
- kernel-api/src/main/scala/org/apache/toree/dependencies/CoursierDependencyDownloader.scala
- project/plugins.sbt
Changed references for Coursier 1.0.0-M12 to version 1.0.0-M14.  Required fixes due to API changes were also made.
> Updated to Coursier 1.0.0-M14

- README.md
> Changed instructions to pip install from apache dist server

- scala-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/scala/ScalaInterpreter.scala
This defines Scala implicits commonly used with Spark SQL. This includes dataframe functions, like `map` or `sum`, common conversions like `Seq#toDF`, and the `$` prefix to coerce strings to column names.
> TOREE-376: Add implicits to the Scala interpreter.

- etc/legal/LICENSE_extras
Review and add missing dependencies on the extended
license used for binary packages
> [TOREE-392] Update LICENSE content for binary packages

- scala-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/scala/ScalaInterpreter.scala
- scala-interpreter/src/test/scala-2.11/scala/ScalaInterpreterSpec.scala
- scala-interpreter/src/test/scala/integration/interpreter/scala/JVMReprSpec.scala
Refactored the configuration storing the truncation magic option and wire it again with the runtime logic
> [TOREE-482] Fix %Truncation magic

- Dockerfile
- etc/examples/notebooks/magic-tutorial.ipynb
- etc/pip_install/toree/toreeapp.py
Remove PySpark and SparkR obsolete references from sample
notebooks.
> Remove obsolete references to PySpark and SparkR

- kernel-api/src/main/scala/org/apache/toree/security/KernelSecurityManager.scala
Remove the portions of Security Manager that restricted the creation of thread groups.  This change also preserves the prevention of calls to `System.exit()` from sub-threads/groups (including those derived from the restricted group) - otherwise such calls from threads in a new thread group can terminate the kernel.
I chose **not** to implement the ability to preserve the existing logic whereby the creation of new groups are prevented (i.e., via a new boolean option `--prevent-new-thread-groups`) since it felt like adding something that probably isn't necessary.  If others disagree or we (eventually) find a good use-case for restoring that kind of functionality, we can add such an option at that time.
> [TOREE-421] Allow thread groups

- .gitignore
- Dockerfile
- Dockerfile.system-test
- Dockerfile.toree-dev
- Makefile
- etc/kernel.json
- etc/tools/.rat-excludes
- Create a proper docker image for dev
- Combine dev/jupyter build tasks into jupyter
- Use JupyterLab as default UI
> [TOREE-511] Rework make jupyter build tasks

- client/src/test/scala/org/apache/toree/kernel/protocol/v5/client/socket/StdinClientSpec.scala
- kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/handler/CommCloseHandlerSpec.scala
- kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/handler/CommMsgHandlerSpec.scala
- kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/handler/CommOpenHandlerSpec.scala
- kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/handler/InputRequestReplyHandlerSpec.scala
- kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/kernel/ActorLoaderSpec.scala
- kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/relay/KernelMessageRelaySpec.scala
- kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/stream/KernelInputStreamSpec.scala
- kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/stream/KernelOuputStreamSpec.scala
- project/Dependencies.scala
Update the following dependencies:
- Akka 2.5.27
- 0MQ 0.4.3
- Spring Framework 5.2.2.RELEASE
> [TOREE-514] Update Toree kernel dependencies

- communication/src/test/scala/org/apache/toree/communication/socket/ZeroMQSocketRunnableSpec.scala
- project/Dependencies.scala
- project/build.properties
- project/plugins.sbt
- scala-interpreter/src/test/scala/integration/interpreter/scala/JVMReprSpec.scala
A few adjustments before building the RC including some dependency updates
> Release 0.3.1 prepare

- .gitignore
> [MINOR][BUILD] Exclude .bsp from git

- communication/src/main/scala/org/apache/toree/communication/socket/ZeroMQSocketRunnable.scala
The previous PR contains some debugging changes. I'm really sorry about that.
> [TOREE-540][FOLLOWUP] Remove accident debugging changes
