apache/incubator-toree

kernel-api/build.sbt
kernel-api/src/main/scala/org/apache/toree/dependencies/CoursierDependencyDownloader.scala
kernel-api/src/main/scala/org/apache/toree/dependencies/DependencyDownloader.scala
kernel-api/src/main/scala/org/apache/toree/dependencies/IvyDependencyDownloader.scala
kernel-api/src/main/scala/org/apache/toree/utils/ArgumentParsingSupport.scala
kernel-api/src/test/scala/org/apache/toree/dependencies/CoursierDependencyDownloaderSpec.scala
kernel/src/main/scala/org/apache/toree/boot/layer/ComponentInitialization.scala
kernel/src/main/scala/org/apache/toree/magic/builtin/AddDeps.scala
kernel/src/test/scala/org/apache/toree/magic/builtin/AddDepsSpec.scala

Adds the following options to %AddDeps:
- `--repository <URL>` to include another repository when downloading
- `--trace` to print out download information
- `--verbose` to print out miscellaneous information
```scala
%AddDeps org.apache.spark spark-streaming-mqtt_2.10 1.5.2 --trace --transitive --repository https://extra-repo.com
```
These options will show up in the help menu. You can provide `--repository` more than once to include more than one additional repository.
Will ignore any malformed URL. Will try repositories provided by `--repository` first before default repositories.

Update dependency downloader

---

.gitignore
kernel-api/src/main/scala/org/apache/toree/kernel/api/DisplayMethodsLike.scala
kernel-api/src/main/scala/org/apache/toree/kernel/api/KernelLike.scala
kernel/src/main/scala/org/apache/toree/boot/layer/HandlerInitialization.scala
kernel/src/main/scala/org/apache/toree/kernel/api/DisplayMethods.scala
kernel/src/main/scala/org/apache/toree/kernel/api/Kernel.scala
kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/CommCloseHandler.scala
kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/CommMsgHandler.scala
kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/CommOpenHandler.scala
kernel/src/test/scala/org/apache/toree/kernel/api/DisplayMethodsSpec.scala
kernel/src/test/scala/org/apache/toree/kernel/api/KernelSpec.scala

This PR adds a couple of functions to the `kernel` object to enable sending rich content to the client. For now it is supporting HTML and Javascript, but also has a generic method to send content of any mime-type that the client can handle.

Added functions to send rich display content to client

---

.travis.yml
kernel-api/build.sbt
project/Common.scala
project/plugins.sbt

Switches dependency resolution/downloading from sbt's default to coursier (what we use for %AddDeps). Much faster, can run in parallel, can work offline using cache (sbt fails often if not online), more easily sandbox dependencies between projects, no global locks (waiting on ~/.ivy2/.sbt.ivy.lock), blah blah blah.

Updated to use coursier for dependency resolution/downloading

---

Makefile
etc/kernel.json

Now we can use `make dev` with docker to run toree without `pip install` and with support for JVM debug

Modified dev target to use docker and allow JVM debugger

---

kernel/src/test/scala/test/utils/SparkContextProvider.scala
protocol/src/test/scala/org/apache/toree/kernel/protocol/v5/content/CompleteReplySpec.scala
protocol/src/test/scala/org/apache/toree/kernel/protocol/v5/content/ConnectReplySpec.scala

ASF strongly recommends to remove @author tags and `created by` because they imply individual ownership. We had better remove them if possible.

[TOREE-282] Remove `Created by` comments from source code

---

Makefile
etc/bin/run.sh
etc/pip_install/toree/toreeapp.py

Enables all interpreters to be installed by default. Users can specify the interpreters they want by providing a comma seperated list:
```
toree install --interpreters=PySpark,SQL
```

[TOREE 256]: Add installation of all interpreters via pip.

---

scala-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/scala/ScalaInterpreter.scala

While working on #15, found out that `def` where getting redefined as `val` after doing an `%addJar`. This PR filters out Symbols that are `sourceMethods`.

Fixed issue with rebinding defs into vals

---

kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/relay/KernelMessageRelay.scala

Resolves [TOREE-272](https://issues.apache.org/jira/browse/TOREE-272) in terms of the kernel freezing on unknown message types.
Tested using `jupyter notebook` and `jupyter console` with Jupyter 4.2.0. Before the fix, an exception would be thrown and the kernel would halt. Now, a warning is printed that the message of type "..." will be ignored.
/cc @lbustelo

Updated kernel message relay to ignore unknown incoming and output messages

---

etc/bin/run.sh
etc/pip_install/toree/toreeapp.py

pip install now has --toree_opts for definig options during install time
run.sh overwrites --toree_opts if the environment variable TOREE_OPTS is defined

[TOREE 297]: Added options during install and runtime

---

client/src/test/scala/org/apache/toree/comm/ClientCommWriterSpec.scala
kernel/src/test/scala/org/apache/toree/comm/KernelCommWriterSpec.scala
kernel/src/test/scala/test/utils/package.scala
macros/src/main/scala/org/apache/toree/annotations/Experimental.scala
macros/src/main/scala/org/apache/toree/annotations/Internal.scala
protocol/src/main/scala/org/apache/toree/comm/CommCallbacks.scala
protocol/src/main/scala/org/apache/toree/comm/CommRegistrar.scala
protocol/src/main/scala/org/apache/toree/comm/CommWriter.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/CommContent.scala
protocol/src/test/scala/org/apache/toree/comm/CommWriterSpec.scala

This PR aims to pass the RAT checking. Currently, it fails like the following.
```
$ etc/tools/check-licenses
Could not find Apache license headers in the following files:
!????? /Users/dongjoon/toree/kernel/src/test/scala/test/utils/package.scala
```
After this PR, that will be.
```
$ etc/tools/check-licenses
RAT checks passed.
```

[MINOR] Remove empty lines before Apache lincense header.

---

pyspark-interpreter/src/main/resources/PySpark/pyspark_runner.py

Applying version-specific switches for Spark 1.4 to Spark 1.5/1.6.
https://issues.apache.org/jira/browse/TOREE-309

Enabling auto convert, Spark SQL imports for Spark 1.5, 1.6

---

etc/kernel.json
etc/pip_install/toree/toreeapp.py
pyspark-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/pyspark/PySparkInterpreter.scala
pyspark-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/pyspark/PySparkProcess.scala
pyspark-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/pyspark/PySparkService.scala

Adds an optional kernel parameter PYTHON_EXEC
````
...
"SPARK_HOME": "/usr/lib/spark",
"PYTHON_EXEC" : "/usr/local/python/virtualenvs/myvenv/bin/python",
...
````
which, if unspecified, uses the previous hard-coded default of `python`.
https://issues.apache.org/jira/browse/TOREE-310

Adding support for custom python exec (e.g. virtualenv)

---

etc/bin/run.sh
plugins/src/main/scala/org/apache/toree/plugins/PluginSearcher.scala

This PR removes the need to have the assembly jar explicitly in the driver classpath. Now the `--driver-class-path` option is free for clients to use when installing Toree. It can be set through the `SPARK_OPTS`.

Remove the need to add assembly to driver-class-path

---

etc/pip_install/toree/toreeapp.py

Fixes https://issues.apache.org/jira/browse/TOREE-302

[skip ci] Default to use SPARK_HOME env during install

---

etc/examples/notebooks/magic-tutorial.ipynb
kernel/src/main/scala/org/apache/toree/boot/layer/ComponentInitialization.scala
kernel/src/main/scala/org/apache/toree/magic/builtin/AddJar.scala
resources/compile/reference.conf
resources/test/reference.conf

Similarly to the logic of add jar this will:
* Allow the user to specify the dependency dir and use that if it exists, else will create a temp dir for that toree process.
* Update the magic-tutorial notebook to reflect the download dir location in the output.

Make add deps installation directory either a specified path or a unique temp path per toree process.

---

kernel/src/main/scala/org/apache/toree/boot/KernelBootstrap.scala
kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/KernelInfoRequestHandler.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/SparkKernelInfo.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/KernelInfoReply.scala
protocol/src/test/scala/org/apache/toree/kernel/protocol/v5/content/KernelInfoReplySpec.scala

When working on [Migrate System Tests To Use Jupyter Kernel Test](https://issues.apache.org/jira/browse/TOREE-296?jql=project%20%3D%20TOREE) it was discovered that the [kernel info spec](http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-info) changed.  
These changes are needed to make the Jupyter tests pass.

Fix kernel info spec message structure due to spec changes.

---

Makefile
test_toree.py

[TOREE 317](https://issues.apache.org/jira/browse/TOREE-317?jql=project%20%3D%20TOREE)
* Overrides execute_helper to allow handling multiline code/streaming output that could exist in an add jar type operation.
* Includes sample custom test other than what is built it in.
* Tests addjar by volume mounting the resource/file.

Add jar kernel test and override execute_helper

---

Makefile
kernel-api/src/main/scala/org/apache/toree/interpreter/Interpreter.scala
kernel-api/src/main/scala/org/apache/toree/interpreter/broker/BrokerService.scala
kernel-api/src/main/scala/org/apache/toree/interpreter/broker/BrokerState.scala
kernel-api/src/test/scala/org/apache/toree/interpreter/broker/BrokerStateSpec.scala
kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/interpreter/tasks/ExecuteRequestTaskActor.scala
kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/interpreter/tasks/ExecuteRequestTaskActorSpec.scala
kernel/src/test/scala/org/apache/toree/magic/builtin/DataFrameSpec.scala
kernel/src/test/scala/test/utils/DummyInterpreter.scala
pyspark-interpreter/src/main/resources/PySpark/pyspark_runner.py
pyspark-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/pyspark/PySparkInterpreter.scala
pyspark-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/pyspark/PySparkService.scala
scala-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/scala/ScalaInterpreter.scala
sparkr-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sparkr/SparkRInterpreter.scala
sparkr-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sparkr/SparkRService.scala
sql-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sql/SqlInterpreter.scala
sql-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sql/SqlService.scala
test_toree.py

[TOREE-318](https://issues.apache.org/jira/browse/TOREE-318)
* Passes the output stream into the BrokerState and maps it to the code_id, so that the interpreter can call sendOutput with the code_id and write to the correct output stream.
* Makes use of python's AST parser to figure out if the last code statement in the request is an expression, if its an expression it will send output to the stream immediately from stdout, else assign the last statement to a temp variable where it is evaluated and if that has output return it as an execute result.
* Added system test coverage using the Jupyter kernel tester, which will test a print statement and a execute result producing arithmetic expression.  Note the kernel tester will test pyspark now as well as scala spark.

Fix pyspark interpreter to handle execute results and output streams correctly.

---

pyspark-interpreter/src/main/resources/PySpark/pyspark_runner.py
test_toree.py

The current python runner is a touch broken, not in the least due to an oddity that can lead to multiple gateways if you create a Python SparkConf object.
This PR aims to address that issue, and as a useful consequence permit more pythonic use of the kernel object:
```
conf = (
SparkConf()
.setMaster("local[1]")
.setAppName("Jupyter PySpark")
)
kernel.createSparkContext(conf)
```

Wrapping the kernel object in a python class

---

kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/magic/MagicParser.scala

Change magicRegex to handle `%` magic line
Before patch (kernel killed)
```
%
java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:347)
at scala.None$.get(Option.scala:345)
at org.apache.toree.kernel.protocol.v5.magic.MagicParser$$anonfun$parseOutInvalidMagics$2.apply(MagicParser.scala:93)
at org.apache.toree.kernel.protocol.v5.magic.MagicParser$$anonfun$parseOutInvalidMagics$2.apply(MagicParser.scala:92)
at scala.collection.immutable.List.map(List.scala:273)
at org.apache.toree.kernel.protocol.v5.magic.MagicParser.parseOutInvalidMagics(MagicParser.scala:92)
at org.apache.toree.kernel.protocol.v5.magic.MagicParser.parseLines(MagicParser.scala:153)
at org.apache.toree.kernel.protocol.v5.magic.MagicParser.parse(MagicParser.scala:174)
at …
```

[TOREE-334] java.util.NoSuchElementException on empty magic

---

protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/SparkKernelInfo.scala

The default spark application name for Toree is still IBM Spark Kernel.

---

kernel/src/test/scala/integration/PostProcessorSpecForIntegration.scala
scala-interpreter/src/main/scala-2.11/org/apache/toree/kernel/interpreter/scala/ScalaInterpreterSpecific.scala

This is a rather ugly fix to address the issue caused by
https://issues.scala-lang.org/browse/SI-8935
The crux of the issue is that valueOfTerm returns None -- always
This introduces a small class that is bound into the REPL scope so that we
can modify its internal state and use that to retrieve values.
We can extend this to a more general case later on if needed.

TOREE-341 Fixed exception stack traces getting lost.

---

scala-interpreter/src/main/scala-2.11/org/apache/toree/kernel/interpreter/scala/ScalaInterpreterSpecific.scala
scala-interpreter/src/test/scala-2.11/scala/ScalaInterpreterSpec.scala

Magics are not working properly on the scala 2.11 / spark 2.0 master branch. For example using the html magic:
`%%html`
`<b>foo</b>`
will return 
`Left(Map(text/html -> <b>foo</b>))`
The problem is in the scala IMain repl used in the 2.11 version of ScalaInterpreterSpecific read method. IMain valueOfTerm is not working properly when given a variable name. IMain eval is working however.

Fix for cell and line magics

---

Makefile
etc/.src-release-ignore
etc/legal/NOTICE_extras
etc/pip_install/setup.py

From @lresende 
```
./scala-interpreter/src/test/resources/ScalaTestJar.jar
./scala-interpreter/src/test/resources/TestJar.jar
./scala-interpreter/src/test/resources/TestJar2.jar
./sparkr-interpreter/src/main/resources/R/pkg/inst/test_support/sparktestjar_2.10-1.0.jar
```
~~- [ ] rat is giving the following unapproved licenses~~
* there is an exclude file that will ignore many of the files below
```
Unapproved licenses:
./.example-image
./.jvmopts
./README.md
./RELEASE_NOTES.md
./derby.log
./index.ipynb
./client/src/main/resources/client-ivy.xml
./client/src/main/resources/toree-client-ivy.xml
./client/src/test/resources/kernel-profiles/IOPubIntegrationProfile.json
./communication/src/main/resources/toree-communication-ivy.xml
./etc/.src-release-ignore
./etc/kernel.json …
```

Changes in responds to feedback on 0.1.0 rc1

---

kernel/src/main/scala/org/apache/toree/Main.scala
project/common.scala
project/plugins.sbt
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/SparkKernelInfo.scala

@lbustelo, @Lull3rSkat3r, @mariusvniekerk This fixes the url needed to publish to the staging repository. We also had the wrong organization name when publishing, so I've resolved that as well.
As for coursier, I was getting binary compatibility issues to do with missing methods. For now, it's disabled (for building our project, not using in our magics).
Will need to update the url and organization name in 0.2.x as well.

Fixed staging url and organization name, disabled coursier due to issues

---

.gitattributes

Git relies on user setting core.autocrlf which
is ususally unreliable as not all users are aware
of this configuration, or they forget to properly set.
The .gitattributes file is a template file with the
appropriate configuration for different file types.
After these changes are applied it's recommended to
do the following commands on your local repository:
git rm --cached -r .
git reset --hard
More info available at
https://help.github.com/articles/dealing-with-line-endings/

Add git configuration for line ending

---

Dockerfile.system-test

CI is currently failing due to system tests.
Check http://unix.stackexchange.com/questions/342403/openjdk-8-jre-headless-depends-ca-certificates-java-but-it-is-not-going-to-be for an explanation of the fix.

Fix system tests

---

kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/CodeCompleteHandler.scala

The start and end positions were swapped, causing the front-ends to
replace no characters from the partial symbol that is completed.

TOREE-379: Fix code completion reply.

---

kernel-api/src/main/scala/org/apache/toree/interpreter/Interpreter.scala
kernel/src/main/scala/org/apache/toree/boot/layer/HandlerInitialization.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/LanguageInfo.scala
pyspark-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/pyspark/PySparkInterpreter.scala
scala-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/scala/ScalaInterpreter.scala
sparkr-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sparkr/SparkRInterpreter.scala
sql-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/sql/SqlInterpreter.scala

This fixes Scala syntax highlighting in Jupyter notebooks. The kernel info reply needs to include a value for "codemirror_mode" that is recognized by CodeMirror. From looking at `CodeMirror.mimeModes` in the console, the correct one for Scala is `text/x-scala`. This also adds the mime type and uses the same value.

TOREE-363: Fix Scala syntax highlighting.

---

kernel/src/main/scala/org/apache/toree/kernel/api/Kernel.scala

Keeping a reference to a SparkSession prevents users from restarting the Spark application in long-running notebooks. This update the kernel so that it always returns the current Spark session from `SparkSession.builder.getOrCreate`.
This also adds a cache of `JavaSparkContext` to avoid creating one every time `javaSparkContext` is called. The cache uses weak keys, so the entries disappear when the Spark session is garbage collected.

TOREE-387: Always use SparkSession.builder.getOrCreate.

---

kernel-api/src/main/scala/org/apache/toree/magic/MagicManager.scala

This adds the error thrown in magic to the log, but not to the jupyter client.

TOREE-377: When magic fails, log the error.

---

kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/IsCompleteHandler.scala
scala-interpreter/src/main/scala-2.11/org/apache/toree/kernel/interpreter/scala/ScalaInterpreterSpecific.scala

This commit includes a bug fix to send indentation instead of the
response twice.
This also updates the is-complete check to require a blank line to end a
multi-line block, which is the way ipython behaves. This avoids running
code when a user intends to continue a block.
Last, this updates the indentation heuristic. First, indentation is
taken from the previous line's starting indentation (before, the first
white space was used). Then, if the interpreter detects `=>` or `{`, it
adds two additional spaces.

TOREE-378: Fix is_complete_handler responses.

---

etc/bin/run.sh

Thanks to @paulovn who discovered and fixed this bug https://github.com/apache/incubator-toree/commit/0eb3bb29fbe5fb533bc9b4bbb720a59362982b30.
As a more general question, do we want to keep the `eval` here? To my understanding, it lets the options contain env variables that will get expanded when toree is started. In a shell environment these options will get expanded anyway and I'm not sure if it is safe to evaluate parameters in general.

Fix: quote application name

---

kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/ShutdownHandler.scala

The `shutdown_reply` message header now includes the protocol version indicator.  Since it was previously only including an empty string, applications that want to adapt different versions on the fly expect a float in that entry.  This change adds that value.

[TOREE-504] Add protocol version to shutdown_reply header

---

.travis.yml

Install of Oracle JDK 8 Failing in Travis CI and as a result,
build is failing for new pull requests.
We just need to add `dist: trusty` in the .travis.yml file
as mentioned in the issue below:
https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038

[TOREE-505] Fix Oracle JDK8 in Travis CI

---

kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/ExecuteRequestHandler.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/package.scala
protocol/src/test/scala/org/apache/toree/kernel/protocol/v5/KMBuilderSpec.scala
scala-interpreter/src/main/scala-2.11/org/apache/toree/kernel/interpreter/scala/ScalaInterpreterSpecific.scala

Fix string values within Metadata, the values needs to be json string.
Reply errors to iopub.error instead of iopub.exec_result

[TOREE-508] Reply errors to iopub.error instead of iopub.exec_result

---

.github/workflows/build.yml
etc/pip_install/setup.py

Traitlets 5.x has been out for quite a while and Toree's use of traitlets (`ToreeApp` derives from class `Application`) is compatible and we shouldn't be downgrading traitlets during toree pip installs.

Remove traitlets version cap

---

.github/workflows/build.yml
kernel-api/src/main/scala/org/apache/toree/dependencies/IvyDependencyDownloader.scala

Fixes [TOREE-530](https://issues.apache.org/jira/browse/TOREE-530)
**OBS**: Uses OpenJDK (temurin) istead of zulu, so unit tests with java 8 passes.
Also fixes https://github.com/apache/incubator-toree/pull/175
Trying to build toree with APACHE_SPARK_VERSION=3.2.1 breaks because of deprecated API.
```
[error] apache/incubator-toree/kernel-api/src/main/scala/org/apache/toree/dependencies/IvyDependencyDownloader.scala:190:9: method retrieve in class Ivy is deprecated
[error]     ivy.retrieve(
[error]         ^
[error] one error found
[error] (kernelApi / Compile / compileIncremental) Compilation failed
[error] Total time: 64 s (01:04), completed Feb 18, 2022, 1:13:46 PM
make: *** [Makefile:108: target/scala-2.12/toree-assembly-0.6.0.dev0-incubating-SNAPSHOT.jar] Error 1 
```

[TOREE-530] Ivy downloader with Spark 3.2.x

---

build.sbt
kernel/build.sbt
plugins/build.sbt
project/CommonPlugin.scala
protocol/build.sbt

Migrate the sbt script from deprecated syntax to slash syntax, to suppress build warnings.
```
[warn] /Users/chengpan/Projects/apache-toree/project/CommonPlugin.scala:37:19: method in in trait ScopingSetting is deprecated (since 1.5.0): `in` is deprecated; migrate to slash syntax - https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash
[warn]       testOptions in UnitTest := Seq(Tests.Filter(unitFilter)),
[warn]                   ^
```

[TOREE-533][BUILD] Migrate sbt script to slash syntax

---

.gitignore

I'm using [pyenv-virtualenv](https://github.com/pyenv/pyenv-virtualenv) to manage the Python virtual environment.
> `.python-version` files are used by pyenv to denote local Python versions ...
ref: https://github.com/pyenv/pyenv-virtualenv#activate-virtualenv

[TOREE-539] Exclude pyenv setting files from git

---

README.md

- change CI badge from Travis to GitHub Action.
- remove unused dead links
- change http to https
- add the missing link of branch 0.4.x

[TOREE-542] Fix links in README

---

Dockerfile.toree-dev

I got failures when running `make dev` on M1 chips MacBook
```
29.95 update-alternatives: error: alternative /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java for java not registered; not setting
```
because for ARM platform, the installed OpenJDK 8 path is `/usr/lib/jvm/java-8-openjdk-arm64` instead of `/usr/lib/jvm/java-8-openjdk-amd64`.
I verified this change locally by run `make dev` on my M1 MacBook, and the CI should verify the change works on x86 platform.

[TOREE-538] apache/toree-dev image supports Applie Silicon

---

Dockerfile
Dockerfile.toree-dev
Makefile
build.sbt
etc/kernel.json
project/Dependencies.scala

This is part of https://github.com/apache/incubator-toree/pull/199
Co-authored-by: Neil Skinner <reqpro@requaos.com>
Co-authored-by: Cheng Pan <chengpan@apache.org>
This PR aims to upgrade the Spark version to 3.3.2
The status of maintained Spark versions are
- Spark 3.0 => EOL
- Spark 3.1 => EOL
- Spark 3.2 => EOL
- Apache Spark 3.3 => December, 2023.
- Apache Spark 3.4 => October, 2024
- Upcoming Apache Spark 3.5 => 18 months from the release
Verified by `make dev`

[TOREE-537] Upgrade Spark 3.3.2

---

communication/src/test/scala/org/apache/toree/communication/socket/ZeroMQSocketRunnableSpec.scala

I noticed the following test failed sometimes, considering the close action is a kind of resource cleanup, we should ignore the error instead of failing the test.
```
[info]   - should set the linger option when provided *** FAILED *** (6 milliseconds)
[info]     java.lang.AssertionError: assertion failed: Runnable is not processing or is closed!
[info]     at scala.Predef$.assert(Predef.scala:223)
[info]     at org.apache.toree.communication.socket.ZeroMQSocketRunnable.close(ZeroMQSocketRunnable.scala:187)
[info]     at org.apache.toree.communication.socket.ZeroMQSocketRunnableSpec.$anonfun$new$15(ZeroMQSocketRunnableSpec.scala:145)
```

[TOREE-549] Fix flaky test by closing pubSocket quietly

---

communication/src/test/scala/org/apache/toree/communication/socket/ZeroMQSocketRunnableSpec.scala

This is the third attempt to fix the test hang issue ...
```
"pool-5-thread-1-ScalaTest-running-ZeroMQSocketRunnableSpec" #76 prio=5 os_prio=0 tid=0x00007efcd5e53000 nid=0x54954 runnable [0x00007efc2effb000]
java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
- locked <0x00000006f93f8448> (a sun.nio.ch.Util$3)
- locked <0x00000006f93f8430> (a java.util.Collections$UnmodifiableSet)
- locked <0x00000006f8c1f180> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
at zmq.Signaler.waitEvent(Signaler.java:166)
at …
```

[TOREE-548] Call shutdown to close ZQM Context in ZeroMQSocketRunnableSpec

---

communication/src/test/scala/org/apache/toree/communication/socket/ZeroMQSocketRunnableSpec.scala

This is the second try to fix the ZeroMQSocketRunnableSpec hang. Unfortunately, the previous try https://github.com/apache/incubator-toree/pull/205 seems not help.
The stacktrace is
```
[info]   - should set the linger option when provided *** FAILED *** (124 milliseconds)
[info]     java.lang.AssertionError: assertion failed: Runnable is not processing or is closed!
[info]     at scala.Predef$.assert(Predef.scala:223)
[info]     at org.apache.toree.communication.socket.ZeroMQSocketRunnable.close(ZeroMQSocketRunnable.scala:187)
[info]     at org.apache.toree.communication.socket.ZeroMQSocketRunnableSpec.$anonfun$new$12(ZeroMQSocketRunnableSpec.scala:138)
...
```
This time I follow the guidance of `ZMQ.Context#close()`'s JavaDoc to set ZMQ_LINGER to 0, hope this help.
> Warning
>
> As …

[TOREE-546] Mitigate ZeroMQSocketRunnableSpec hang

---

scala-interpreter/build.sbt
scala-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/scala/ScalaInterpreter.scala
scala-interpreter/src/test/scala/integration/interpreter/scala/JVMReprSpec.scala

This PR fixes and enables `JVMReprSpec` by doing the following things 
1. Fix the binding issue by changing `Kernel` to `KernelLike`, as the provided instance is `mock[KernelLike]`, the `Kernel` causes assignment failure
```
23/08/10 00:09:16 ERROR ScalaInterpreter: Set failed in bind(kernel, org.apache.toree.kernel.api.Kernel, Mock for KernelLike, hashCode: 381550865)
23/08/10 00:09:16 ERROR ScalaInterpreter: scala.tools.nsc.interpreter.IMain$ReadEvalPrint$EvalException: Failed to load '$line4.$eval': $line4.$eval
at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.evalError(IMain.scala:757)
at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.load(IMain.scala:761)
at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.evalClass$lzycompute(IMain.scala:764)
...
```
2. execute tests using fork …

[TOREE-543] Fix and enable JVMReprSpec

---

scala-interpreter/build.sbt
scala-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/scala/ScalaInterpreter.scala
scala-interpreter/src/test/scala/integration/interpreter/scala/JVMReprSpec.scala

Reverts apache/incubator-toree#209
It fixes the UT, but unfortunately, breaks the real workload ...
We need to explore another way to adjust the test case, or change the implementation.

Revert "[TOREE-543] Fix and enable JVMReprSpec"

---

project/Dependencies.scala

Upgrading Akka to 2.6.21 to prepare to support Scala 2.13, typesafe-config is upgraded to 1.4.2 correspondingly.
Akka 2.6.21 is the latest version released under the Apache V2 license. Since 2.7.0, Akka changed the license from Apache V2 to BSL v1.1, the latter is not allowed by Apache projects.
In the future, we may consider migrating to Apache Pekko due to license issues.
> Apache Pekko is a fork of [Akka](https://github.com/akka/akka) 2.6.x, prior to the Akka project’s adoption of the Business Source License.
https://www.thestack.technology/akka-license-change-lightbend-opensource/
https://apache.org/legal/resolved.html#category-x
https://pekko.apache.org/what-is-pekko.html

[TOREE-550] Upgrade Akka 2.6.21

---

kernel/src/main/scala/org/apache/toree/magic/builtin/BuiltinLoader.scala
kernel/src/main/scala/org/apache/toree/utils/ClassPath.java
project/Dependencies.scala

This PR proposes to downgrade Guava 14.0.1 to align with Apache Spark.
The previous Guava upgrade is to make the `ClassPath` compatible with Java 11, https://github.com/google/guava/issues/3249. As a workaround, this PR fork a `ClassPath` from Guava v32.1.2 to make it happy with Java 11.
Upgrading Guava in Spark is a "Mission Impossible" at the current stage. See details at SPARK-44811 SPARK-36676
The current tests do not cover the use cases of Spark with Hive, and based on the above Spark tickets, the Guava upgrading would break Hive usage

[TOREE-552] Downgrade Guava 14.0.1 to align with Spark

---

client/src/main/scala/org/apache/toree/kernel/protocol/v5/client/socket/StdinClient.scala
kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/CommInfoRequestHandler.scala
kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/KernelInfoRequestHandler.scala
kernel/src/main/scala/org/apache/toree/kernel/protocol/v5/handler/ShutdownHandler.scala
kernel/src/test/scala/org/apache/toree/kernel/protocol/v5/handler/InputRequestReplyHandlerSpec.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/CommInfoReply.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/CompleteReply.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/ConnectReply.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/ConnectRequest.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/ExecuteReply.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/HistoryReply.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/InspectReply.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/IsCompleteReply.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/KernelInfoReply.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/ReplyContent.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/ShutdownReply.scala
protocol/src/main/scala/org/apache/toree/kernel/protocol/v5/content/package.scala
protocol/src/test/scala/org/apache/toree/kernel/protocol/v5/content/HistoryReplySpec.scala
protocol/src/test/scala/org/apache/toree/kernel/protocol/v5/content/InputReplySpec.scala
protocol/src/test/scala/org/apache/toree/kernel/protocol/v5/content/KernelInfoReplySpec.scala
protocol/src/test/scala/org/apache/toree/kernel/protocol/v5/content/ShutdownReplySpec.scala

This PR refers to https://jupyter-client.readthedocs.io/en/latest/messaging.html to revise the Jupyter message protocol implementation
> All reply messages have a 'status' field ...
A trait `ReplyContent` is introduced to make sure all reply messages meet this contract.
One exception is "connect_reply", because
> Deprecated since version 5.1: connect_request/reply have not proved useful, and are considered deprecated. Kernels are not expected to implement handlers for this message.
https://jupyter-client.readthedocs.io/en/latest/messaging.html#connect

[TOREE-541] Reply message should implement status field

---

Makefile

This PR aims to improve the developer experience of the command `make dev`.
Previously, after changing the code, running `make dev` does not pick up the new assembly artifacts, which is not convenient for developers.
After the change, `make dev` becomes intuitive, it always picks up the latest assembly artifacts.

[TOREE-553] Correct the behavior of `make dev`

---

scala-interpreter/src/main/scala/org/apache/toree/kernel/interpreter/scala/ScalaInterpreter.scala

When a caller instantiates `Toree Main` and `ScalaInterpreter`, they may want to use a custom classloader to execute specific code within `ScalaInterpreter`. To facilitate this, the caller can pass a custom classloader through the current thread’s `ContextClassLoader`.
For example, in a Spark environment, all Spark framework jars are typically located in a directory such as `/opt/spark/jars`, which also includes `toree-assembly.jar`. When we submit a Spark job (e.g., using `spark-submit --conf spark.jars=MyExternalJar.jar --class org.apache.toree.Main`), any custom jars like `MyExternalJar.jar` are added by `SparkSubmit.scala` to the current thread’s `ContextClassLoader`. This classloader is then used to execute `org.apache.toree.Main` and instantiate `ScalaInterpreter` with access to the …

[TOREE-558] ScalaInterpreter prefer to use context classloader

---

NOTICE

probably needs https://github.com/apache/incubator-toree/pull/227 because the CI is now broken without that

[TOREE-562] Update NOTICE for 2025
